#!/bin/bash
# Multi-Model Router — 완전 자동 설치 스크립트
# Usage: bash ~/Projects/a-team/scripts/multi-model/install.sh
#
# 이 스크립트는 순차적으로:
# 1. Ollama 설치 및 모델 다운로드
# 2. LiteLLM 프록시 설치 및 설정
# 3. OpenRouter 연결 (API 키 필요)
# 4. Claude Code 통합
# 5. 시작 스크립트 생성

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"
LOG_FILE="$HOME/.ateam/multi-model-install.log"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[$(date '+%H:%M:%S')]${NC} $*" | tee -a "$LOG_FILE"; }
success() { echo -e "${GREEN}✓${NC} $*" | tee -a "$LOG_FILE"; }
warn() { echo -e "${YELLOW}⚠${NC} $*" | tee -a "$LOG_FILE"; }
error() { echo -e "${RED}✗${NC} $*" | tee -a "$LOG_FILE"; exit 1; }

mkdir -p "$(dirname "$LOG_FILE")"
echo "=== Multi-Model Router Install $(date) ===" >> "$LOG_FILE"

# ═══════════════════════════════════════════════════════════════
# Phase 0: 사전 조건 확인
# ═══════════════════════════════════════════════════════════════

log "Phase 0: 사전 조건 확인..."

# Homebrew
if ! command -v brew &>/dev/null; then
    error "Homebrew 필요. 설치: /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
fi
success "Homebrew 확인"

# Python 3.10+
if ! command -v python3 &>/dev/null; then
    error "Python3 필요. 설치: brew install python@3.11"
fi
PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
success "Python $PY_VER 확인"

# pip
if ! command -v pip3 &>/dev/null; then
    warn "pip3 없음, 설치 중..."
    python3 -m ensurepip --upgrade
fi
success "pip3 확인"

# ═══════════════════════════════════════════════════════════════
# Phase 1: Ollama
# ═══════════════════════════════════════════════════════════════

log "Phase 1: Ollama 설치..."

if command -v ollama &>/dev/null; then
    success "Ollama 이미 설치됨: $(ollama --version)"
else
    log "Ollama 설치 중..."
    brew install ollama
    success "Ollama 설치 완료"
fi

# Ollama 서버 시작 (이미 실행 중이면 스킵)
if ! pgrep -f "ollama serve" &>/dev/null; then
    log "Ollama 서버 시작..."
    ollama serve &>/dev/null &
    sleep 3
fi

# 서버 상태 확인
if curl -s http://localhost:11434/api/tags &>/dev/null; then
    success "Ollama 서버 실행 중 (localhost:11434)"
else
    error "Ollama 서버 시작 실패"
fi

# 모델 다운로드
log "모델 다운로드 (시간 소요)..."

MODELS=("qwen2.5-coder:7b" "qwen2.5-coder:14b")
for model in "${MODELS[@]}"; do
    if ollama list 2>/dev/null | grep -q "$model"; then
        success "$model 이미 존재"
    else
        log "$model 다운로드 중..."
        ollama pull "$model"
        success "$model 다운로드 완료"
    fi
done

# ═══════════════════════════════════════════════════════════════
# Phase 2: LiteLLM
# ═══════════════════════════════════════════════════════════════

log "Phase 2: LiteLLM 설치..."

if pip3 show litellm &>/dev/null; then
    success "LiteLLM 이미 설치됨"
else
    log "LiteLLM 설치 중..."
    pip3 install 'litellm[proxy]' --quiet
    success "LiteLLM 설치 완료"
fi

# 설정 파일 생성
log "LiteLLM 설정 파일 생성..."
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_DIR/litellm-config.yaml" << 'LITELLM_CONFIG'
# LiteLLM Multi-Model Router Configuration
# Generated by A-Team install.sh

model_list:
  # ═══ Local Models (Ollama) ═══
  - model_name: local-fast
    litellm_params:
      model: ollama/qwen2.5-coder:7b
      api_base: http://localhost:11434
    model_info:
      description: "Fast local model for summaries, formatting, simple edits"

  - model_name: local-strong
    litellm_params:
      model: ollama/qwen2.5-coder:14b
      api_base: http://localhost:11434
    model_info:
      description: "Strong local model for coding tasks"

  # ═══ Claude Models (Direct) ═══
  - model_name: claude-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      description: "Top tier - architecture, complex decisions"

  - model_name: claude-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      description: "Mid tier - implementation, bug fixes"

  # ═══ OpenRouter Fallback ═══
  - model_name: openrouter-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      description: "Fallback when Anthropic rate limited"

  - model_name: openrouter-cheap
    litellm_params:
      model: openrouter/meta-llama/llama-3.1-70b-instruct
      api_key: os.environ/OPENROUTER_API_KEY
    model_info:
      description: "Cheap batch processing"

router_settings:
  routing_strategy: "usage-based-routing"
  enable_pre_call_checks: true
  num_retries: 2
  timeout: 120

  # Fallback chain
  fallbacks:
    - local-fast: [local-strong, claude-sonnet]
    - local-strong: [claude-sonnet]
    - claude-sonnet: [openrouter-sonnet]
    - claude-opus: [claude-sonnet]

general_settings:
  master_key: "${LITELLM_MASTER_KEY:-sk-ateam-local}"

litellm_settings:
  drop_params: true
  set_verbose: false
  max_budget: 50.0
  budget_duration: "1d"
LITELLM_CONFIG

success "LiteLLM 설정 완료: $CONFIG_DIR/litellm-config.yaml"

# ═══════════════════════════════════════════════════════════════
# Phase 3: 시작/정지 스크립트
# ═══════════════════════════════════════════════════════════════

log "Phase 3: 관리 스크립트 생성..."

# 시작 스크립트
cat > "$SCRIPT_DIR/start.sh" << 'START_SCRIPT'
#!/bin/bash
# Multi-Model Router 시작
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="$SCRIPT_DIR/config/litellm-config.yaml"
PID_DIR="$HOME/.ateam/pids"
LOG_DIR="$HOME/.ateam/logs"

mkdir -p "$PID_DIR" "$LOG_DIR"

echo "Starting Multi-Model Router..."

# 1. Ollama
if ! pgrep -f "ollama serve" &>/dev/null; then
    echo "Starting Ollama..."
    ollama serve >> "$LOG_DIR/ollama.log" 2>&1 &
    echo $! > "$PID_DIR/ollama.pid"
    sleep 2
fi
echo "✓ Ollama: http://localhost:11434"

# 2. LiteLLM
if ! pgrep -f "litellm --config" &>/dev/null; then
    echo "Starting LiteLLM proxy..."
    litellm --config "$CONFIG" --port 4000 >> "$LOG_DIR/litellm.log" 2>&1 &
    echo $! > "$PID_DIR/litellm.pid"
    sleep 2
fi
echo "✓ LiteLLM: http://localhost:4000"

# 상태 확인
echo ""
echo "=== Status ==="
curl -s http://localhost:11434/api/tags | jq -r '.models[].name' 2>/dev/null | while read m; do
    echo "  Ollama: $m"
done
curl -s http://localhost:4000/health 2>/dev/null && echo "  LiteLLM: healthy" || echo "  LiteLLM: starting..."

echo ""
echo "Dashboard: http://localhost:4000/ui"
START_SCRIPT

chmod +x "$SCRIPT_DIR/start.sh"
success "시작 스크립트: $SCRIPT_DIR/start.sh"

# 정지 스크립트
cat > "$SCRIPT_DIR/stop.sh" << 'STOP_SCRIPT'
#!/bin/bash
# Multi-Model Router 정지

PID_DIR="$HOME/.ateam/pids"

echo "Stopping Multi-Model Router..."

if [ -f "$PID_DIR/litellm.pid" ]; then
    kill $(cat "$PID_DIR/litellm.pid") 2>/dev/null && echo "✓ LiteLLM stopped"
    rm -f "$PID_DIR/litellm.pid"
fi

# Ollama는 다른 용도로 쓸 수 있으니 선택적
read -p "Ollama도 정지할까요? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    pkill -f "ollama serve" 2>/dev/null && echo "✓ Ollama stopped"
    rm -f "$PID_DIR/ollama.pid"
fi

echo "Done."
STOP_SCRIPT

chmod +x "$SCRIPT_DIR/stop.sh"
success "정지 스크립트: $SCRIPT_DIR/stop.sh"

# 상태 확인 스크립트
cat > "$SCRIPT_DIR/status.sh" << 'STATUS_SCRIPT'
#!/bin/bash
# Multi-Model Router 상태 확인

echo "=== Multi-Model Router Status ==="
echo ""

# Ollama
echo "Ollama:"
if pgrep -f "ollama serve" &>/dev/null; then
    echo "  Status: Running"
    echo "  Endpoint: http://localhost:11434"
    echo "  Models:"
    ollama list 2>/dev/null | tail -n +2 | while read line; do
        echo "    - $line"
    done
else
    echo "  Status: Stopped"
fi

echo ""

# LiteLLM
echo "LiteLLM:"
if pgrep -f "litellm --config" &>/dev/null; then
    echo "  Status: Running"
    echo "  Endpoint: http://localhost:4000"
    echo "  Dashboard: http://localhost:4000/ui"
    health=$(curl -s http://localhost:4000/health 2>/dev/null)
    [ -n "$health" ] && echo "  Health: $health"
else
    echo "  Status: Stopped"
fi

echo ""

# 환경변수
echo "Environment:"
[ -n "$ANTHROPIC_API_KEY" ] && echo "  ANTHROPIC_API_KEY: set" || echo "  ANTHROPIC_API_KEY: NOT SET"
[ -n "$OPENROUTER_API_KEY" ] && echo "  OPENROUTER_API_KEY: set" || echo "  OPENROUTER_API_KEY: NOT SET"
STATUS_SCRIPT

chmod +x "$SCRIPT_DIR/status.sh"
success "상태 스크립트: $SCRIPT_DIR/status.sh"

# ═══════════════════════════════════════════════════════════════
# Phase 4: 환경변수 안내
# ═══════════════════════════════════════════════════════════════

log "Phase 4: 환경 설정..."

ENV_FILE="$HOME/.ateam/multi-model.env"
cat > "$ENV_FILE" << 'ENV_TEMPLATE'
# Multi-Model Router 환경변수
# 이 파일을 편집하고 ~/.zshrc 또는 ~/.bashrc에 source 추가

# Anthropic (기존 Claude 키)
export ANTHROPIC_API_KEY="your-anthropic-key"

# OpenRouter (https://openrouter.ai 에서 발급)
export OPENROUTER_API_KEY="sk-or-..."

# LiteLLM 마스터 키 (로컬용, 임의 설정)
export LITELLM_MASTER_KEY="sk-ateam-local"

# Claude Code가 LiteLLM 프록시 사용 (선택)
# export ANTHROPIC_BASE_URL="http://localhost:4000"
ENV_TEMPLATE

success "환경변수 템플릿: $ENV_FILE"

# ═══════════════════════════════════════════════════════════════
# Phase 5: launchd 자동 시작 (선택)
# ═══════════════════════════════════════════════════════════════

PLIST_DIR="$HOME/Library/LaunchAgents"
PLIST_FILE="$PLIST_DIR/com.ateam.multi-model.plist"

mkdir -p "$PLIST_DIR"

cat > "$PLIST_FILE" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.ateam.multi-model</string>
    <key>ProgramArguments</key>
    <array>
        <string>$SCRIPT_DIR/start.sh</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$HOME/.ateam/logs/multi-model-launchd.log</string>
    <key>StandardErrorPath</key>
    <string>$HOME/.ateam/logs/multi-model-launchd.err</string>
</dict>
</plist>
PLIST

success "launchd plist 생성: $PLIST_FILE"
log "자동 시작 활성화: launchctl load $PLIST_FILE"

# ═══════════════════════════════════════════════════════════════
# 완료
# ═══════════════════════════════════════════════════════════════

echo ""
echo "═══════════════════════════════════════════════════════════"
echo -e "${GREEN}Multi-Model Router 설치 완료!${NC}"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "다음 단계:"
echo ""
echo "1. 환경변수 설정:"
echo "   vim ~/.ateam/multi-model.env"
echo "   # OPENROUTER_API_KEY 입력"
echo "   echo 'source ~/.ateam/multi-model.env' >> ~/.zshrc"
echo "   source ~/.zshrc"
echo ""
echo "2. 시작:"
echo "   bash $SCRIPT_DIR/start.sh"
echo ""
echo "3. 상태 확인:"
echo "   bash $SCRIPT_DIR/status.sh"
echo ""
echo "4. (선택) 자동 시작 활성화:"
echo "   launchctl load $PLIST_FILE"
echo ""
echo "5. 테스트:"
echo "   curl http://localhost:4000/health"
echo "   curl http://localhost:4000/v1/models"
echo ""
echo "로그: $LOG_FILE"
